AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Description of your lambda function
Resources:
  TicketWsCmiCallback:
    Type: AWS::Serverless::Function
    Properties:
      Handler: go-lambda
      Runtime: go1.x
      CodeUri: .
      Events:
        CallbackCMI:
          Type: Api
          Properties:
            Path: /my-function-path
            Method: post